# Generated by Django 5.1.7 on 2025-04-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
